### ISSUE TITLE
Change Path.PathSeparator to Path.DirectorySeparatorChar

### ISSUE THREAD

**Issue by mikebrind** [salarcode/DotAvifConvertor#1]
https://github.com/salarcode/DotAvifConvertor/blob/aedc8dfdb8b54e663b2397696ace050b086f2fdc/DotAvifConverter/AvifConverter.cs#L15C24-L15C37

`Path.PathSeparator` is used to separate path strings in environment variables, and on Windows, this results in `;`,  so `CheckBinaryRoot` always failing.

Use `Path.DirectorySeparatorChar` instead which will generate the file path separator - `\\` on Windows.

**Comment by salarcode** [comment]
Thanks, updated now
